### ISSUE TITLE
"conn is not a function" error when creating a new group

### ISSUE THREAD

**Issue by shuheif** [OpenEnergyDashboard/OED#347]
I'm getting "conn is not a function" error when creating a new group. This is because getDB func should not have () when it is used as conn variable inside methods. 
Related to #346 

`[ERROR@2018-09-21T19:00:34.895Z] Error while inserting new group BatchError 
    stat: { total: 5, succeeded: 0, failed: 5, duration: 2 }
    errors: [
        0: TypeError: conn is not a function
            at Function.getByID (/usr/src/app/src/server/models/Meter.js:76:21)
`

**Comment by NoraCodes** [comment]
It should be passed in as a function and called inside model methods. E.g.:

```
function whatever(arg1, arg2, conn = getDB) {
    conn().whatever(arg1, arg2)...
}
```

That is, the function should be called _at the time the model method is called_, rather than _at the time the model method is created_ which is what would happen if one wrote:

```
function whatever(arg1, arg2, conn = getDB()) {
    conn.whatever()
}
```

**Comment by shuheif** [comment]
I agree that it should be called inside model methods as your first example. I guess the problem is not the parenthesis but the other part of the code. Below is the error message I got when I tried to create a new group.

```
[ERROR@2018-09-24T20:24:26.484Z] Error while inserting new group BatchError {
    stat: { total: 4, succeeded: 0, failed: 4, duration: 0 }
    errors: [
        0: TypeError: conn is not a function
            at Function.getByID (/usr/src/app/src/server/models/Meter.js:76:21)
            at Group.adoptMeter (/usr/src/app/src/server/models/Group.js:127:29)
            at req.body.childMeters.map.mid (/usr/src/app/src/server/routes/groups.js:146:71)
            at Array.map (<anonymous>)
            at Task.getDB.tx (/usr/src/app/src/server/routes/groups.js:146:51)
            at <anonymous>
            at process._tickCallback (internal/process/next_tick.js:118:7)
        1: TypeError: conn is not a function
            at Function.getByID (/usr/src/app/src/server/models/Meter.js:76:21)
            at Group.adoptMeter (/usr/src/app/src/server/models/Group.js:127:29)
            at req.body.childMeters.map.mid (/usr/src/app/src/server/routes/groups.js:146:71)
            at Array.map (<anonymous>)
            at Task.getDB.tx (/usr/src/app/src/server/routes/groups.js:146:51)
            at <anonymous>
            at process._tickCallback (internal/process/next_tick.js:118:7)
        2: TypeError: conn is not a function
            at Function.getByID (/usr/src/app/src/server/models/Meter.js:76:21)
            at Group.adoptMeter (/usr/src/app/src/server/models/Group.js:127:29)
            at req.body.childMeters.map.mid (/usr/src/app/src/server/routes/groups.js:146:71)
            at Array.map (<anonymous>)
            at Task.getDB.tx (/usr/src/app/src/server/routes/groups.js:146:51)
            at <anonymous>
            at process._tickCallback (internal/process/next_tick.js:118:7)
        3: TypeError: conn is not a function
            at Function.getByID (/usr/src/app/src/server/models/Meter.js:76:21)
            at Group.adoptMeter (/usr/src/app/src/server/models/Group.js:127:29)
            at req.body.childMeters.map.mid (/usr/src/app/src/server/routes/groups.js:146:71)
            at Array.map (<anonymous>)
            at Task.getDB.tx (/usr/src/app/src/server/routes/groups.js:146:51)
            at <anonymous>
            at process._tickCallback (internal/process/next_tick.js:118:7)
    ]
}
Stacktrace: 
BatchError: conn is not a function
    at check (/usr/src/app/node_modules/spex/lib/ext/batch.js:133:32)
    at step (/usr/src/app/node_modules/spex/lib/ext/batch.js:107:17)
    at /usr/src/app/node_modules/spex/lib/ext/batch.js:82:17
    at /usr/src/app/node_modules/spex/lib/utils/index.js:62:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by simonbtomlinson** [comment]
This is because pg-promise creates its own transaction objects with the same signature as the db object, and we were setting `conn = db` to support that. When you wrapped `db` with a function, you didn't make sure that things supported those transaction objects, and now they're getting invoked like a function whenever they're used.

You guys should either globally mock the db object, or use dependency injection in a factory that creates the model classes, and pass the correct db object in there. Mocking is likely easier.

**Comment by NoraCodes** [comment]
Thanks for weighing in, Simon. I didn't realize you could just mock out the connection object; I thought only library objects (e.g. transactions) could do that. This is definitely the right solution.

**Comment by shuheif** [comment]
How do we change to use the db object without causing the same issue in #346?

**Comment by simonbtomlinson** [comment]
@LeoTindall I think you can mock out anything that gets exported, but I'm not super familiar with it, and I haven't really looked at your `getDB` fix. I can take a better look later.
