### ISSUE TITLE
app hangs if no meter data

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#480]
If you try to select a meter (it may also happen with groups but not tested) when there are no readings for that meter you get in the console:

> [ERROR@2020-04-17T22:51:21.555Z] Unhandled Promise Rejection: error: cannot subtract infinite timestamps
> Stacktrace: 
> error: cannot subtract infinite timestamps
>     at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:539:11)
>     at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:366:17)
>     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:105:22)
>     at Socket.emit (events.js:209:13)
>     at addChunk (_stream_readable.js:305:12)
>     at readableAddChunk (_stream_readable.js:286:11)
>     at Socket.Readable.push (_stream_readable.js:220:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
> 
> (node:102) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)

and the app hangs where the bouncing circles never stop. While this will only happen with a new or empty meter, we should check for this condition (if it does not slow down the application) and protect for it.

**Comment by huss** [comment]
While testing this to update, I found the issue is gone. There is no error in the console/log and the app does not hang. You do get an empty graphic with strange axis values but that isn't that bad (nice to fix at some point). It looks like:
![Screen Shot 2022-01-20 at 7 33 38 PM](https://user-images.githubusercontent.com/987062/150449589-f92b8850-3fd6-4075-947e-1328d5fab361.png)
Thus, it appears changes to the code fixed this. As such, it is now being closed.
