### ISSUE TITLE
refreshReadingViews with bad IP address causes error

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#518]
If a meter is enabled and has a dummy (non-existant IP address) then refreshReadingViews causes an error. I may only happen for MAMAC meter type. If you set enabled to false then it works fine. I have briefly looked at the code and it is unclear why this is happening.

**Comment by huss** [comment]
I've reduced the importance of this for a couple of reasons. First, real sites should never have a MAMAC meter with bad IP address. Second, OED now has several meter types including other so dummy meters should not be part of the refresh process at this point.

**Comment by huss** [comment]
First, the issue should have referenced updateMamacMeters and not refreshReadingsViews. I just tested this out to update the issue. I gave two meters the meter_type of mamac, enabled of true and no ip address. The result was:

```
$ oedrun updateMamacMeters
[+] Running 1/0
 ⠿ Container oed-huss-database-1  Running                                                                                                                                                                                        0.0s

> Open-Energy-Dashboard@0.8.0 updateMamacMeters /usr/src/app
> node ./src/server/services/updateMamacMeters.js

[INFO@2022-01-21T01:22:31.510Z] Fetching new Mamac meter data

[INFO@2022-01-21T01:22:31.620Z] Getting meter data 2022-01-21T01:22:31.620Z

[ERROR@2022-01-21T01:22:31.624Z] ERROR ON REQUEST TO METER [NO IP ADDRESS AVAILABLE], [object Object] doesn't have an IP address to read data from
Stacktrace: 
Error: [object Object] doesn't have an IP address to read data from
    at readMamacData (/usr/src/app/src/server/services/readMamacData.js:40:9)
    at /usr/src/app/src/server/services/updateMeters.js:28:19
    at Array.map (<anonymous>)
    at updateAllMeters (/usr/src/app/src/server/services/updateMeters.js:28:6)
    at updateMamacMeters (/usr/src/app/src/server/services/updateMamacMeters.js:22:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

[ERROR@2022-01-21T01:22:31.630Z] ERROR ON REQUEST TO METER [NO IP ADDRESS AVAILABLE], [object Object] doesn't have an IP address to read data from
Stacktrace: 
Error: [object Object] doesn't have an IP address to read data from
    at readMamacData (/usr/src/app/src/server/services/readMamacData.js:40:9)
    at /usr/src/app/src/server/services/updateMeters.js:28:19
    at Array.map (<anonymous>)
    at updateAllMeters (/usr/src/app/src/server/services/updateMeters.js:28:6)
    at updateMamacMeters (/usr/src/app/src/server/services/updateMamacMeters.js:22:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

[INFO@2022-01-21T01:22:31.631Z] Update finished
```

Thus, it did loop over both meters and generated an error for both. The error was caught, logged and OED continued as desired. It isn't the cleanest way to deal with this but this error should be rare and the admin should fix the IP address when they get a log update with the error. As such, this issue is no longer a problem and is being closed.
