### ISSUE TITLE
test error with pg-promise upgrade

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#527]
PR #507 introduced failures in the test code that need to be resolved. They do not appear to be real errors in OED but new issues with the test code that may involve moment. The output of the issues is:

> 1) MomentJS patching
>        patches moment durations:
> 
>       AssertionError: expected 'unknown' to equal 'interval'
>       + expected - actual
> 
>       -unknown
>       +interval
>       
>       at Context.<anonymous> (src/server/test/db/momentPatchTests.js:15:19)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (internal/process/task_queues.js:85:5)
> 
>   2) MomentJS patching
>        patches arrays of moment durations:
> 
>       AssertionError: expected 'text[]' to equal 'interval[]'
>       + expected - actual
> 
>       -text[]
>       +interval[]
>       
>       at Context.<anonymous> (src/server/test/db/momentPatchTests.js:22:19)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (internal/process/task_queues.js:85:5)
> 
>   3) MomentJS patching
>        patches returned durations to moment duration types:
> 
>       AssertionError: expected false to equal true
>       + expected - actual
> 
>       -false
>       +true
>       
>       at Context.<anonymous> (src/server/test/db/momentPatchTests.js:29:42)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (internal/process/task_queues.js:85:5)
> 
>   4) MomentJS patching
>        patches durations to the correct value:
>      TypeError: returned.toISOString is not a function
>       at Context.<anonymous> (src/server/test/db/momentPatchTests.js:36:52)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (internal/process/task_queues.js:85:5)
> 
>   5) readings API
>        for bar charts
>          for meters
>            returns nothing for meters that do not exist:
>      AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
>       at Context.<anonymous> (src/server/test/web/readings.js:64:25)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (internal/process/task_queues.js:85:5)
> 
>   6) readings API
>        for bar charts
>          for groups
>            returns nothing for groups that do not exist:
>      AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
>       at Context.<anonymous> (src/server/test/web/readings.js:88:25)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by huss** [comment]
One of the fixes in PR #502 fixes these issues so this is now complete and just awaiting merging.
